### ISSUE TITLE
astropy's isiterable cannot be imported by lenstromy with astropy == 6.1.3

### ISSUE THREAD

**Issue by Ferr013** [ajshajib/dolphin#44]
Lenstromy imports the function `isiterable` from astropy in [lenstronomy.Cosmo.cosmo_interp.py](http://lenstronomy.cosmo.cosmo_interp.py/).
This import fails when `astropy version > 5`, the solution is [commented out in the last version on github](https://github.com/lenstronomy/lenstronomy/blob/main/lenstronomy/Cosmo/cosmo_interp.py).
I suggest requiring `astropy <= 5` in [requirements.txt](https://github.com/ajshajib/dolphin/blob/master/requirements.txt)

**Comment by ajshajib** [comment]
Closing based on #43.
