### ISSUE TITLE
log=True in processor.swim() stalls the execution

### ISSUE THREAD

**Issue by Ferr013** [ajshajib/dolphin#47]
I noticed that when I turn on the flag `log=True` while calling `processor.swim()` in a jupyter notebook, the code seems to run the PSO and the MCMC, but then stalls, and I have to force quit the kernel.
I tested it both on my data and on the basic example[ lens_system1](https://github.com/ajshajib/dolphin/tree/master/io_directory_example/data/lens_system1) provided in the dolphin repo.
Since when I try to stop the execution the kernel crashes, I was not able to see the error dump and I cannot tell what caused it.
I am using the latest commit `dolphin 12c5859`. I have not tested it running within a .py file.

Example with `log=False`:
<img width="1155" alt="Screenshot 2024-09-04 at 7 27 40 AM" src="https://github.com/user-attachments/assets/f2cbc329-7cd1-44aa-82e7-2e6df1afc7c0">
Example with `log=True`:
<img width="1161" alt="Screenshot 2024-09-04 at 7 29 10 AM" src="https://github.com/user-attachments/assets/4f668616-598c-42a0-8704-c6170e347976">
<img width="1165" alt="Screenshot 2024-09-04 at 7 29 29 AM" src="https://github.com/user-attachments/assets/893e39d6-7464-4e52-81f5-ac93b0e6b442">

**Comment by ajshajib** [comment]
Hi @Ferr013, thanks a lot for reporting the issue. First of all, the `log=True` was not meant to be used in a notebook. Notebooks already have the outputs being printed out underneath a cell. The intended production mode of use for `dolphin` is to be run from a script on an HPC; in that case, the print-outs are saved in a log file with `log=True`.  Notebooks can of course be used for interactive testing of the features and for post-processing of the outputs.

Now, making `log=True` with notebooks can take a little work around: https://stackoverflow.com/questions/66739794/jupyter-lab-running-cell-forever-with-file-close-print-and-sys-stdout. Making this possible directly from within `dolphin` is not at the top of my priority list, but you are more than welcome to implement it if you need this feature ASAP.

For now, I will add in the documentation of `log` that it should not be set `True` when running from a notebook.

**Comment by ajshajib** [comment]
The documentation has been updated with #50.
