### ISSUE TITLE
Possible issue with order of the lens model

### ISSUE THREAD

**Issue by chinyitan** [ajshajib/dolphin#8]
I noticed that in the `lens_system1.config.yml` file  if replace 

      `model: lens:- 'SPEP' - 'SHEAR_GAMMA_PSI'`

 with

      `model: lens:' - 'SHEAR_GAMMA_PSI' - 'SPEP`

dolphin outputs an error "derivatives() got an unexpected keyword argument 'center_x'", shouldnt dolphin work regardless of the order of the lens profile?

**Comment by ajshajib** [comment]
It might actually be `lenstronomy` that requires the first mass profile to be of the galaxy and not external shear.

**Comment by sibirrer** [comment]
> It might actually be `lenstronomy` that requires the first mass profile to be of the galaxy and not external shear.

This is required in a setting with a solver PROFILE_SHEAR only, meaning when lenstronomy solves for some of the parameters in these profiles given constraints from 4 image positions. For other solvers, the main deflector profile needs to be first too

**Comment by ajshajib** [comment]
Thanks @sibirrer for the confirmation.

**Comment by ajshajib** [comment]
Added documentation in the example config files through PR #10 to clarify the `lenstronomy` requirement.
